import Testing
@testable import Day07

struct Day07Tests {
    private let exampleInput = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

    @Test func testPart1Example() {
        let day = Day07(input: exampleInput)
        #expect(day.part1() == 21)
    }

    @Test func testPart2Example() {
        let day = Day07(input: exampleInput)
        #expect(day.part2() == 40)
    }
}
